packages:
  - apps/web
  - packages/contracts
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.3'
  - '@turbo/darwin-arm64@2.11.3'
  - '@turbo/linux-64@2.11.3'
  - '@turbo/linux-arm64@2.11.3'
  - '@turbo/windows-64@2.11.3'
  - '@turbo/windows-arm64@2.11.3'
  - '@voidzero-dev/vite-plus-core@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-darwin-arm64@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-darwin-x64@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-linux-x64-musl@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@1.0.0-rc.0'
  - turbo@2.11.3
  - vite-plus@1.0.0-rc.0
